import blueprint
import random

al_ahly = blueprint.Team("Al Ahly FC", "https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Al_Ahly_SC_logo.svg/640px-Al_Ahly_SC_logo.svg.png", "Egypt")
wydad = blueprint.Team("Wydad AC", "https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Wydad_AC_crest_%282022%29.svg/1200px-Wydad_AC_crest_%282022%29.svg.png", "Marocco")
esperance = blueprint.Team ("Espérance Sportive de Tunis", "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Espérance_Sportive_de_Tunis_logo.png/250px-Espérance_Sportive_de_Tunis_logo.png", "Tunis")
mamelodi = blueprint.Team ("Mamelodi Sundowns FC", "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Mamelodi_Sundowns_F.C.svg/1200px-Mamelodi_Sundowns_F.C.svg.png", "South Africa")
al_hilal = blueprint.Team("Al Hilal SFC", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Al-Hilal_SFC_logo.svg/1200px-Al-Hilal_SFC_logo.svg.png", "Saudi Arabia")
urawa = blueprint.Team ("Urawa Red Diamonds", "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Urawa_Red_Diamonds_logo.svg/640px-Urawa_Red_Diamonds_logo.svg.png", "Urawa")
al_ain = blueprint.Team ("Al Ain FC", "https://upload.wikimedia.org/wikipedia/en/6/62/Al_Ain_FC_logo_2024.png", "United Arab Emirates")
ulsan = blueprint.Team("Ulsan HD", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Ulsan_Hyundai_FC.svg/1200px-Ulsan_Hyundai_FC.svg.png", "Korea")
chelsea = blueprint.Team ("Chelsea FC", "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png", "England")
real_madrid = blueprint.Team ("Real Madrid", "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png")
man_city = blueprint.Team ("Manchester City", "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png")
b_munich = blueprint.Team("Bayern Munich", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_München_logo_%282024%29.svg/250px-FC_Bayern_München_logo_%282024%29.svg.png")
paris = blueprint.Team ("Paris", "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/1200px-Paris_Saint-Germain_F.C..svg.png")
inter = blueprint.Team ("Inter", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png")
porto = blueprint.Team("FC Porto", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Ulsan_Hyundai_FC.svg/1200px-Ulsan_Hyundai_FC.svg.png", "Korea")
atl_matrid = blueprint.Team ("Atletico Madrid", "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Atletico_Madrid_Logo_2024.svg/1200px-Atletico_Madrid_Logo_2024.svg.png")
benfica = blueprint.Team("Benfica", "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/SL_Benfica_logo.svg/1200px-SL_Benfica_logo.svg.png")
b_dortmund = blueprint.Team("Borussia Dortmund", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png")
juventus = blueprint.Team("Juventus", "https://upload.wikimedia.org/wikinews/en/d/d2/Juventus_Turin.svg")